### ISSUE TITLE
autotick bot errored: source distribution files missing on PyPI

### ISSUE THREAD

**Issue by nhchan** [conda-forge/torchmetrics-feedstock#31]
It appears that the [regro-cf-autotick-bot](https://github.com/regro/autotick-bot) encountered an error whilst trying to get to the latest version of torchmetrics (1.0.1 as of this writing). The error displayed on the [status page (under "ERRORED")](https://conda-forge.org/status/#version_updates) is as follows:

```
4.00 attempts - The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '1.0.1' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
```

It appears that the source distribution files have been absent on PyPI since release 1.0.0, but exist on the project's GitHub release page.

**Comment by Borda** [comment]
addressed in https://github.com/pypa/gh-action-pypi-publish/issues/170#issuecomment-1634428841
